### PR TITLE
Sars sov2 docker

### PR DESCRIPTION
**Pull request by uweschmitt**
See also `docker/README.md`

Image size on my machine < 1GB.

### CODE REVIEW

**Comment by kpj** [comment]
Great, thanks!

In `docker/README.md` it says:
```
Technical note: the .snakemake folder is mounted into the current working directory
   on the host. Thus conda packages and conda environments are not created within
   the container but on the host file system.
   This reduces container size and persists state between different calls of 
   vpipe_docker.sh
```
Does this mean that the Docker container will need an internet connection when executed for the first time?

Is the plan to eventually couple this to the GitHub Container registry and automatically publish new builds via GitHub Actions?

**Comment by uweschmitt** [comment]
> Does this mean that the Docker container will need an internet connection when executed for the first time?

yes. But setting up an alternative container with the packages included is easy.
 
> Is the plan to eventually couple this to the GitHub Container registry and automatically publish new builds via GitHub Actions?

Yes, would be the goal.

**Comment by kpj** [comment]
> > Does this mean that the Docker container will need an internet connection when executed for the first time?
> 
> yes. But setting up an alternative container with the packages included is easy.
> 
> > Is the plan to eventually couple this to the GitHub Container registry and automatically publish new builds via GitHub Actions?
> 
> Yes, would be the goal.

Wonderful, we should definitely head both these ways. I'll wait for @DrYak for further reviews.

**Comment by uweschmitt** [comment]
> yes. But setting up an alternative container with the packages included is easy.

I discovered one issue yesterday, and I think @DrYak mentioned this during the previous in person discussions: It looks like `--conda-create-envs-only` is broken in the current version of snakemake. In my case it does not setup any conda environments.

**Comment by uweschmitt** [comment]
I pushed an update version. The new version includes all needed conda packages in the image. Imagesize on my Mac: 5.77GB.

**Comment by kpj** [comment]
Thanks a lot again!
We have integrated your PR and #72 into master.

**Pull request closed without merging**
