### PR TITLE
Quasispecies Reconstruction Benchmark

### PR DESCRIPTION
**Pull request by kpj**
This PR is the home of the quasispecies reconstruction benchmark workflow.
Eventually, it will make its way to master.

### CODE REVIEW

**Comment by DrYak** [comment]
@kpj : If I am not mistaken, most of the benchmark was merged together with the big merge for @LaraFuhrmann 's workshop.

By now the benchmark is already in V-pipe

And this old PR is deprecated. Am I correctly presuming?

**Comment by kpj** [comment]
Not sure what was merged in the workshop PR.

**Comment by DrYak** [comment]
Okay got-it:

fa3b74e5533cb24cc58d572119d7b2c1d0a6feb9 from this branch is the last one that is merged into master (as-is, no rebase, just merge).

from 230b90c81171ca1f94fbfca93fb0b386e6f819bc onward to 7eb83a434e086bb8ea9f15f84ed9a77b928b504e is not yet in master.

As the feature-benchmark as merged as-is (no rebase), adding them on top shouldn't be that difficult. (Probably not too many conflict except for linting-related stuff).

Will start merging in as soon as v2.99.3 is out now.

**Comment by DrYak** [comment]
I managed to merge.
Indeed, most of discepencies were `snakefmt` linting, and the [switching to `runtime` resource by snakemake](https://github.com/cbg-ethz/V-pipe/commit/fd1f76fd84dfe08bb79fa77f27e3b6426e72f6bd#diff-86d02bdd878e820e8eeeb517956dc1ac4aac2d658fd80403af3ea37f7d19edd6).

Now in rubicon as of e844fa6d1c505cd8db03c2831d8df30ad85df979

**Pull request merged**
