### PR TITLE
init project relies on bashism

### PR DESCRIPTION
**Pull request by DrYak**
- fixes troubles on distributions using `dash` (mostly Debian family)

### CODE REVIEW

**Comment by DrYak** [comment]
@sposadac 

I am getting the following message, probably because Github distinguishes between pushes from command line and merges from the GUI ?

```
remote: error: GH006: Protected branch update failed for refs/heads/sars-cov2-dev.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
```

Also, for the `sars-cov2-dev` branch, could you add one or two more contributors, e.g.: @kpj , @monicadragan , @pedrofale or @NBMueller ?

**Comment by sposadac** [comment]
This is expected. The idea is to work with PRs.
Of course everyobody can contribute, but as we discussed in the meeting you are the person resposible for reviewing the PRs.

**Comment by DrYak** [comment]
For `sars-cov2-dev` it would be good to have one extra person that is neither you or me in order to be more nimble and enable quick response, such as to the current problem (affecting both Aashil and marcovth)

For the current problem, `checkbashisms` is a nice tool to better understand the problem.

on Debian and Ubuntu systems, the shell that provides `/bin/sh` has recently been switched to  `dash` (and this has somewhat been missed on the last round of VM tests I have been doing, proof that CI/CD is in dire need), whereas on most other systems it is either `bash` or `zsh`. 

It turns out, even when in POSIX mode, none of the above are perfectly POSIX compliant.

For the details:

- the brace expansion `{a,b}` is  an extension and thus the search function doesn't work as-is on Ubuntu.
- ditto for the source with argument `. activate 'env'` used load the environment at the beginning of  `vpipe`.
- also the `-a` parameter  of exec isn't supported either, though that one is purely cosmetic and isn't required.
- finally bash supports its own regex library and I plan to use that in future upgrade of init_project.
- dash doesn't expand `~` as thoroughly as other shells and it might confuse users used to the interactive shell. 

Given that we already rely on bash for the installtion itself ( `[[` tests, pattern matches, etc.) I think it is reasonable to do it there too, even more so as bash is still available on machines that switched to zsh (e.g.: mac OS X) and both zsh and bash support the same extensions.

Some of the above restrictions could be have POSIX-compliant workarounds, but I would not feel comfortable until we have a good CI/CD in place to mass-test them on all Linux distro combinations.

**Comment by DrYak** [comment]
As extra information:

 - notice that `snakemake` defaults to [using bash for its shell rules](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#rules), that's why `mv *R{_1,1}*` works.
 - dash was specifically written to run extremely fast the SysVinit style multiple boot scripts (when a large amount of shell scripts are simultaneously launched as part of Debian's boot process, it's desirable to rely on a much smaller and faster shell than bash, and `#!/bin/sh` should be strictly POSIX-compliant anyway) but it's definitely not our case.

**Comment by sposadac** [comment]
Sure. I also noticed the `-a` parameter of exec is not supoprted, but I forgot to inlcude it in the previous revision. Can you retarget this PR to master?

**Comment by DrYak** [comment]
Will do.

**Pull request closed without merging**
