### PR TITLE
Sars cov2 ci regression test

### PR DESCRIPTION
**Pull request by uweschmitt**
I setup github-actions to run a simple regression tests based on the `test_data/pos_M*` files. 

The test runs the sars-cov2 pipeline on these files and compares the `samples/pos_M*/20200729/variants/SNVs/snvs.vcf` to a recorded *TOBE* output from a single run on my computer.

The comparison is done using `diff` such that comment lines which vary over runs are ignored.

The testing pipeline finally uploads the snakemake output and (in case test fails) the diffs as artefacts of  the workflow.

Please check https://github.com/uweschmitt/V-pipe/actions/runs/879117904 to see how the workflow runs and one should also see the artefacts.

### CODE REVIEW

**Comment by kpj** [comment]
This looks great! I checked the workflow run and was able to download the artefacts!

Do you think it would make sense to also include linting/formatting using https://github.com/snakemake/snakefmt in this GitHub Actions workflow?
Also, would it be useful to use the official Snakemake GitHub Actions workflow (https://github.com/snakemake/snakemake-github-action) here?

**Comment by uweschmitt** [comment]
> This looks great! I checked the workflow run and was able to download the artefacts!
> 
> Do you think it would make sense to also include linting/formatting using https://github.com/snakemake/snakefmt in this GitHub Actions workflow?

Linting: definitely. 

Formatting: I'd set this up for pull requests. Alternatively we could setup pre-commit hooks in git itself.

> Also, would it be useful to use the official Snakemake GitHub Actions workflow (https://github.com/snakemake/snakemake-github-action) here?

I looked at this and it looks pretty basic, I'll check if it supports all functionalities we need (such as setting up extra conda channels)....

**Comment by uweschmitt** [comment]
> Formatting: I'd set this up for pull requests. Alternatively we could setup pre-commit hooks in git itself.

I had another look at this and it would require to commit and push within an github action which makes me feel uncomfortable since this could theoretically lead to merge conflicts. Any opinion on that?

**Comment by kpj** [comment]
I'd also be against automatically pushing formatting fixes, but I think the formatting summary could also be included in the GitHub Actions run. I.e., the GA workflow fails if there are formatting changes.
This would be similar to how, e.g., https://github.com/nvuillam/mega-linter handles linting and formatting (when auto-fixes are disabled).

**Comment by kpj** [comment]
> I checked it and it complicated more than it helped. I looks like I would have to rearrange folder structures etc to make the volume mounts from the action compatible with the current split between the snake make files and the actual V-pipe project.

That's fair! Let's stick to our solution then and not use snakemake/snakemake-github-action.

**Comment by DrYak** [comment]
As of commit #b5050f8813718d1da5e3e1bf8044b311a4866e98 this has been successfully rebased and merged into our "rubicon" branch (the big merging effort for all these new features).

**Comment by kpj** [comment]
We tested it, and it works 🎉

**Pull request closed without merging**
