### PR TITLE
Add additional visualization capabilities

### PR DESCRIPTION
**Pull request by kpj**

### CODE REVIEW

**Comment by sposadac** [comment]
Can you please keep your change sets to the minimal? I see some of the changes are reshuffling lines in the files, is this really necessary? We will have to merge this branch into master at some point no too soon in the future, so having concise diffs is likely to make our lives easier then.

**Comment by kpj** [comment]
I discussed this earlier with @DrYak. What does he think now?

**Comment by sposadac** [comment]
Unfortunately, I am not aware of any of such discussions. As I said before, the master branch is in the process of being stabilized now. Therefore, at this stage, let's focus on adding the functionalities needed to work with sars-cov2 (i.e. visualization and data import). The sars-cov2 branch will be separate from master for a longer while until it is mature and ready to be merged back into master (the long-term goal should be supporting sars-cov2 without breaking things for HIV or other viruses). The simpler the diff will look at this point in time the easier the review process is going to be.

**Comment by kpj** [comment]
That makes sense :)
I'll put it into another PR, and we can later see whether it's necessary.

**Comment by DrYak** [comment]
We discussed with Björn Grüning (one of the bioconda authors), and he explained to us that the conda-forge absolutely needs to be at a higher priority otherwise things break.

So the channel re-ordering is critical, but indeed could go in the main branch.

**Comment by sposadac** [comment]
Thanks @kpj!
As I said, necessary changes (fixes) are okay, but so far the current code works and, in fact, I have encountered problems in which a different ordering resulted in problems. Therefore, I prefer not to touch a working code unless we are absolutely sure about what we are doing.

**Comment by DrYak** [comment]
This ordering (conda-forge above bioconda) is the accepted one that everybody has to use according to conda authors. 
Without this, we had weird failure where the wrong version of biopython is installed on Mac OS X and ShoRAH gets downgrded to 1.1.3. 
Every package in the bioconda repository, when mass-built, should be built against this channel order, which means that the same order should be used for installing dependencies upon deployment of package.

(we could deduce that any package that fails in this order and require a different order permutation should be considered a bug in bioconda, If that happens, it means some recipes need to be upgraded)

**Pull request closed without merging**
